# Generated by Django 5.0.6 on 2024-07-04 10:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('WFTE', 'Waiting for the employee'), ('INPR', 'In progress'), ('COMP', 'Completed')], default='WFTE', max_length=4)),
                ('report', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('assign_task', 'Can assign the tasks'), ('change_task_status', 'Can change the status of tasks'), ('close_task', 'Can completed a task by setting its status as completed')],
            },
        ),
    ]
